
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-16
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-16
pull_requests: [{"author":{"id":"U_kgDOBtnpoQ","is_bot":false,"login":"li-kelly","name":""},"headRefName":"kl-menudatabase","number":56,"title":"created database for menu items","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/56"},{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-menureviews-formtablecomp","number":55,"title":"Rp menureviews formtablecomp","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/55"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"user-specific-review-retrieval","number":54,"title":"Implement User-Specific Review Retrieval Functionality","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/54"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"sa-moderate-placeholderpage","number":53,"title":"Sa moderate placeholderpage","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/53"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"review_controller_post_and_getAll","number":52,"title":"Review controller post and get all","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/52"},{"author":{"id":"U_kgDOBtJfBw","is_bot":false,"login":"cs11111111","name":""},"headRefName":"Claire-feat2Back","number":51,"title":"UpdateAlias and Moderation for feature#2 Backend","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/51"},{"author":{"id":"U_kgDOB3E0Rw","is_bot":false,"login":"ttnguyen908","name":"Tiffany Nguyen"},"headRefName":"4th-Epic-Backend-1","number":50,"title":"Epic #4 Backend 1 - DiningCommons API Service + Endpoint for GET ALL implementation","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/50"},{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-menureviews-fixtures","number":49,"title":"Created Review Fixtures with review instances.","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/49"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"delte_un-needed_files","number":37,"title":"cleaning repo ~  unneeded files","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/37"}]
