
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-16
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pconrad-patch-3","number":76,"title":"Update 82-kanban-slack-update.yml","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/76"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"sa-pages-portola","number":69,"title":"Sa pages portola","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/69"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"sa-pages-ortega","number":68,"title":"Sa pages ortega","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/68"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"sa-pages-delaguerra","number":67,"title":"Sa pages delaguerra","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/67"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"sa-pages-diningcommons","number":66,"title":"sa - added dropdown for commons on nav bar and added carrillo page an…","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/66"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"delte_un-needed_files","number":37,"title":"cleaning repo ~  unneeded files","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/37"}]
