
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-16
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-16
pull_requests: [{"author":{"id":"U_kgDOB3D13A","is_bot":false,"login":"rohanpreetam","name":""},"headRefName":"rp-menureviews-fixtures","number":49,"title":"Created Review Fixtures with review instances.","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/49"},{"author":{"id":"U_kgDOBtnpoQ","is_bot":false,"login":"li-kelly","name":""},"headRefName":"kl-entrees","number":45,"title":"Epic 3 Backend 2: Created a service and controller that uses it which returns the items on the menu","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/45"},{"author":{"id":"U_kgDOB3Ckdw","is_bot":false,"login":"Salshriaan","name":""},"headRefName":"sa-myreviews-indexpage","number":43,"title":"sa - added placeholder index page for myreviews and tested","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/43"},{"author":{"id":"U_kgDOBtnpoQ","is_bot":false,"login":"li-kelly","name":""},"headRefName":"kl-diningmenuservice","number":42,"title":"Created a UCSBDiningMenuService that gets meal times and a controller endpoint that uses that service","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/42"},{"author":{"id":"U_kgDOBtJfBw","is_bot":false,"login":"cs11111111","name":""},"headRefName":"Claire-Test-Test","number":41,"title":"updatealias and moderation value for feature #2","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/41"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"delte_un-needed_files","number":37,"title":"cleaning repo ~  unneeded files","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/37"},{"author":{"id":"MDQ6VXNlcjgyMzMyNjk2","is_bot":false,"login":"jayster7101","name":"Jayden"},"headRefName":"review-entity","number":34,"title":"Created the Entity for the Review table","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-16/pull/34"}]
